name: First workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello
        run: echo "Hello All"
      - name: printing bye
        run: echo "good bye"
